### ISSUE TITLE
Add plugins mention and underline 

### ISSUE THREAD

**Issue by ilasHoven** [ckeditor/ckeditor5-build-balloon#25]
Please add mention and underline plugins to the balloon build.

**Comment by Mgsy** [comment]
Hi, we provide a basic set of plugins in our builds. If you want to extend it, please take a look at our [installing plugins guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build). After reading it, you'll be able to add extra plugins to your build.
