### ISSUE TITLE
Resize toolbar for media?

### ISSUE THREAD

**Issue by carlo-fontanos** [ckeditor/ckeditor5-build-balloon#31]
Hi,

Is there a way to add a toolbar for resizing media elements? something similar to the toolbar for resizing images: 

`https://ckeditor.com/docs/ckeditor5/latest/features/image.html#image-styles`

![image](https://user-images.githubusercontent.com/12164593/63088276-0cef2480-bf87-11e9-98a8-6f08b70b3967.png)

Currently the media appears in full width.

Carl

**Comment by Mgsy** [comment]
@oleq, is there some easy way to achieve it via `MediaEmbedToolbar`?

**Comment by oleq** [comment]
ATM `MediaEmbedToolbar` is used by the comments feature only. 

There's no media feature corresponding to [ImageStyle](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagestyle-ImageStyle.html) plugin but, OFC, this is a valid feature request.

**Comment by oleq** [comment]
And this should land in ckeditor5-media-embed.

**Comment by Mgsy** [comment]
I've opened a feature request in `ckeditor5-media-embed` repository - https://github.com/ckeditor/ckeditor5-media-embed/issues/90. Let's move the discussion there.
